### ISSUE TITLE
Why should we +20 and +40 to generate the layout?

### ISSUE THREAD

**Issue by sunnyHelen** [hbutsuak95/monolayout#18]
https://github.com/hbutsuak95/monolayout/blob/5339d5f7e8f7fbc8272bd96abba16d6128b42098/preprocessing/argoverse/generate_groundtruth.py#L96

when we generate the layout like this, where is the ego camera?
![stereo_front_left_315967327184444000_finish](https://user-images.githubusercontent.com/28101548/133584276-edb360b5-dfe5-404e-a128-f01042dc8964.png)

**Comment by manila95** [comment]
Considering the center (0,0) is at the bottom left end of the image. The ego-vehicle/camera is at (0,resolution/2) or the bottom mid of the image. If the layout resolution is (256, 256) then the ego-camera will be at (0, 128). 

Sorry for the late response!
