### ISSUE TITLE
About depth estimation

### ISSUE THREAD

**Issue by Heimine** [hbutsuak95/monolayout#4]
Hi guys, thanks for the fantastic idea and wonderful work! 
I noticed that in your paper, you mentioned about depth estimation using MonoDepth2, but in this github repo, I didn't find any related codes with depth or disparity map... So I'm wondering if I missed something or you already have the depth map image data and load that somewhere in the dataloader?
Thanks a lot!

**Comment by krrish94** [comment]
Hi @Heimine,

Thanks for your interest! Yeah, we performed a couple of experiments using monodepth2 for "data preparation". Since that was merely confined to an ablation analysis in the paper, we didn't polish the code for release yet.

However, if that's something people would be interested in, we'd be happy to share it.

**Comment by Heimine** [comment]
Hi thanks for the quick reply!
So without using depth information as "data preparation", you could still get the excellent result shown in your paper? 
And I'm curious that when you use the depth information,  did you feed it to the encoder to extract features alongside the raw image? Or process it somewhere else in the network?
Thanks a lot for answering! Once again, I'm really impressed by your results!

**Comment by krrish94** [comment]
We indeed use depth information in our data prep pipeline! If you look closely into Table 2 (page 8 of our [arXiv draft](https://arxiv.org/pdf/2002.08394.pdf)), we investigate the impact of the "source" of depth data.

We consider the following four sources
1. per-frame monodepth2 estimates
2. temporally fused monodepth2 estimates
3. per-frame lidar
4. temporally fused lidar

These depths aren't fed into the model as inputs. They're used as "weak ground-truth" (as even fused lidar doesn't capture all scene points). A discriminator is trained alongside, with rasterized "openstreetmap" layouts as "real" data, encouraging our encoder to predict layouts that resemble openstreetmap data, and overlap with the weak ground-truth.

**Comment by krrish94** [comment]
As an aside: our prepared data is available here, as stated in the README https://www.google.com/url?q=https://drive.google.com/file/d/1KhqsHbruE16BFEiIcvtbzuXxKGMbxogk/view?usp%3Dsharing&sa=D&source=hangouts&ust=1586514007721000&usg=AFQjCNGaBbJtbNyVWhv2Zf7AwKeKz-xBJQ

**Comment by Heimine** [comment]
Thank you very much!
