### ISSUE TITLE
Reagrding generating ground truths for this project.

### ISSUE THREAD

**Issue by gowriaddepalli** [hbutsuak95/monolayout#5]
Hi. This is a really interesting project. Is there any chance you could share the code for generating the targets/weak ground truths using Monodepth. Would be very helpful. Thanks!

**Comment by krrish94** [comment]
@gowriaddepalli thanks for raising this! We didn't imagine the dataprep pipeline would be of interest to others too. We'll be happy to clean-up and release our data preprocessing pipeline as well.

Heads-up: Might take some time, since most co-authors are now dispersed across timezones.

**Comment by krrish94** [comment]
Closing. Dataprep scripts now available.
